### PR TITLE
Filter for capf

### PR DESCRIPTION
**Pull request by jojojames**

### CODE REVIEW

**Comment by jojojames** [comment]
@aaronjensen Continuing from. https://github.com/jojojames/fussy/issues/17

@buzztaiki Thoughts if you had any would be appreciated too.

**Comment by buzztaiki** [comment]
Is the purpose of this fix for speed? If so, I think you can use shortcut at the beginning of `fussy-all-completions` when `string` is an empty string.

Also, a bug report. When I complete (with an empty string) in a following state in the `*scratch*` buffer:

```
(
 ^cursor is here
```

A following error was occurred:

```
Debugger entered--Lisp error: (args-out-of-range "" 0 1)
```

<details>

<summary>Backtrace</summary>

```
Debugger entered--Lisp error: (args-out-of-range "" 0 1)
  substring("" 0 1)
  (format "^%s" (substring str 0 1))
  (list (format "^%s" (substring str 0 1)))
  fussy-pattern-first-letter("")
  (let* ((beforepoint (substring string 0 point)) (afterpoint (substring string point)) (bounds (completion-boundaries beforepoint table pred afterpoint)) (prefix (substring beforepoint 0 (car bounds))) (infix (concat (substring beforepoint (car bounds)) (substring afterpoint 0 (cdr bounds)))) (completion-regexp-list (fussy-pattern-first-letter infix)) (completions (all-completions "" table pred)) (pattern (if (fussy--using-pcm-highlight-p) (progn (let* ((basic-pattern ...) (pattern ...)) (completion-pcm--optimize-pattern (completion-flex--make-flex-pattern pattern))))))) (list completions pattern prefix))
  fussy-filter-capf("" #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil 0)
  funcall(fussy-filter-capf "" #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil 0)
  (let* ((metadata (completion-metadata string table pred)) (cache (if (memq (completion-metadata-get metadata 'category) '(file project-file)) flx-file-cache flx-strings-cache)) (beforepoint (substring string 0 point)) (afterpoint (substring string point)) (bounds (completion-boundaries beforepoint table pred afterpoint)) (infix (concat (substring beforepoint (car bounds)) (substring afterpoint 0 (cdr bounds)))) (val (funcall fussy-filter-fn string table pred point))) (progn (ignore (consp val)) (let* ((x156 (car-safe val)) (x157 (cdr-safe val))) (progn (ignore (consp x157)) (let* ((x158 (car-safe x157)) (x159 (cdr-safe x157))) (progn (ignore (consp x159)) (let* (... ...) (progn ... ...))))))))
  (progn (let* ((metadata (completion-metadata string table pred)) (cache (if (memq (completion-metadata-get metadata 'category) '(file project-file)) flx-file-cache flx-strings-cache)) (beforepoint (substring string 0 point)) (afterpoint (substring string point)) (bounds (completion-boundaries beforepoint table pred afterpoint)) (infix (concat (substring beforepoint (car bounds)) (substring afterpoint 0 (cdr bounds)))) (val (funcall fussy-filter-fn string table pred point))) (progn (ignore (consp val)) (let* ((x156 (car-safe val)) (x157 (cdr-safe val))) (progn (ignore (consp x157)) (let* ((x158 ...) (x159 ...)) (progn (ignore ...) (let* ... ...))))))))
  (or (input-pending-p) (progn (let* ((metadata (completion-metadata string table pred)) (cache (if (memq (completion-metadata-get metadata ...) '...) flx-file-cache flx-strings-cache)) (beforepoint (substring string 0 point)) (afterpoint (substring string point)) (bounds (completion-boundaries beforepoint table pred afterpoint)) (infix (concat (substring beforepoint (car bounds)) (substring afterpoint 0 (cdr bounds)))) (val (funcall fussy-filter-fn string table pred point))) (progn (ignore (consp val)) (let* ((x156 (car-safe val)) (x157 (cdr-safe val))) (progn (ignore (consp x157)) (let* (... ...) (progn ... ...))))))))
  (setq val (or (input-pending-p) (progn (let* ((metadata (completion-metadata string table pred)) (cache (if (memq ... ...) flx-file-cache flx-strings-cache)) (beforepoint (substring string 0 point)) (afterpoint (substring string point)) (bounds (completion-boundaries beforepoint table pred afterpoint)) (infix (concat (substring beforepoint ...) (substring afterpoint 0 ...))) (val (funcall fussy-filter-fn string table pred point))) (progn (ignore (consp val)) (let* ((x156 ...) (x157 ...)) (progn (ignore ...) (let* ... ...))))))))
  (let ((throw-on-input 'input) val) (setq val (or (input-pending-p) (progn (let* ((metadata (completion-metadata string table pred)) (cache (if ... flx-file-cache flx-strings-cache)) (beforepoint (substring string 0 point)) (afterpoint (substring string point)) (bounds (completion-boundaries beforepoint table pred afterpoint)) (infix (concat ... ...)) (val (funcall fussy-filter-fn string table pred point))) (progn (ignore (consp val)) (let* (... ...) (progn ... ...))))))) (cond ((eq quit-flag throw-on-input) (setq quit-flag nil) t) (quit-flag nil) (t val)))
  (catch 'input (let ((throw-on-input 'input) val) (setq val (or (input-pending-p) (progn (let* ((metadata ...) (cache ...) (beforepoint ...) (afterpoint ...) (bounds ...) (infix ...) (val ...)) (progn (ignore ...) (let* ... ...)))))) (cond ((eq quit-flag throw-on-input) (setq quit-flag nil) t) (quit-flag nil) (t val))))
  (let ((inhibit-quit nil)) (catch 'input (let ((throw-on-input 'input) val) (setq val (or (input-pending-p) (progn (let* (... ... ... ... ... ... ...) (progn ... ...))))) (cond ((eq quit-flag throw-on-input) (setq quit-flag nil) t) (quit-flag nil) (t val)))))
  (condition-case nil (let ((inhibit-quit nil)) (catch 'input (let ((throw-on-input 'input) val) (setq val (or (input-pending-p) (progn (let* ... ...)))) (cond ((eq quit-flag throw-on-input) (setq quit-flag nil) t) (quit-flag nil) (t val))))) (quit (setq quit-flag t) (eval '(ignore nil))))
  (let* ((val (condition-case nil (let ((inhibit-quit nil)) (catch 'input (let (... val) (setq val ...) (cond ... ... ...)))) (quit (setq quit-flag t) (eval '(ignore nil)))))) (cond ((null val) 'nil) ((eq val 't) 'nil) (t (let ((collection val)) (if (consp collection) collection nil)))))
  fussy-all-completions("" #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil 0)
  #f(compiled-function (style) #<bytecode 0x11b931998e993cfb>)(fussy)
  completion--some(#f(compiled-function (style) #<bytecode 0x11b931998e993cfb>) (fussy))
  completion--nth-completion(2 "" #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil 0 (metadata (category . company-elisp) (display-sort-function . identity) (cycle-sort-function . identity)))
  #<subr completion-all-completions>("" #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil 0 (metadata (category . company-elisp) (display-sort-function . identity) (cycle-sort-function . identity)))
  apply(#<subr completion-all-completions> ("" #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil 0 (metadata (category . company-elisp) (display-sort-function . identity) (cycle-sort-function . identity))))
  completion-all-completions("" #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil 0 (metadata (category . company-elisp) (display-sort-function . identity) (cycle-sort-function . identity)))
  apply(completion-all-completions ("" #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil 0 (metadata (category . company-elisp) (display-sort-function . identity) (cycle-sort-function . identity))))
  (cons (apply #'completion-all-completions args) hl)
  (progn (fset 'orderless-highlight-matches vnew) (cons (apply #'completion-all-completions args) hl))
  (unwind-protect (progn (fset 'orderless-highlight-matches vnew) (cons (apply #'completion-all-completions args) hl)) (fset 'orderless-highlight-matches old))
  (let* ((vnew #'(lambda (pattern cands) (let ((regexps ...)) (setq hl #'...)) cands)) (old (symbol-function 'orderless-highlight-matches))) (unwind-protect (progn (fset 'orderless-highlight-matches vnew) (cons (apply #'completion-all-completions args) hl)) (fset 'orderless-highlight-matches old)))
  (if (and (fboundp 'orderless-highlight-matches) (fboundp 'orderless-pattern-compiler)) (let* ((vnew #'(lambda (pattern cands) (let (...) (setq hl ...)) cands)) (old (symbol-function 'orderless-highlight-matches))) (unwind-protect (progn (fset 'orderless-highlight-matches vnew) (cons (apply #'completion-all-completions args) hl)) (fset 'orderless-highlight-matches old))) (cons (apply #'completion-all-completions args) hl))
  (progn (fset #'completion-pcm--hilit-commonality vnew) (if (and (fboundp 'orderless-highlight-matches) (fboundp 'orderless-pattern-compiler)) (let* ((vnew #'(lambda (pattern cands) (let ... ...) cands)) (old (symbol-function 'orderless-highlight-matches))) (unwind-protect (progn (fset 'orderless-highlight-matches vnew) (cons (apply #'completion-all-completions args) hl)) (fset 'orderless-highlight-matches old))) (cons (apply #'completion-all-completions args) hl)))
  (unwind-protect (progn (fset #'completion-pcm--hilit-commonality vnew) (if (and (fboundp 'orderless-highlight-matches) (fboundp 'orderless-pattern-compiler)) (let* ((vnew #'(lambda ... ... cands)) (old (symbol-function 'orderless-highlight-matches))) (unwind-protect (progn (fset 'orderless-highlight-matches vnew) (cons (apply ... args) hl)) (fset 'orderless-highlight-matches old))) (cons (apply #'completion-all-completions args) hl))) (fset #'completion-pcm--hilit-commonality old))
  (let* ((vnew #'(lambda (pattern cands) (setq hl #'(lambda ... ...)) cands)) (old (symbol-function #'completion-pcm--hilit-commonality))) (unwind-protect (progn (fset #'completion-pcm--hilit-commonality vnew) (if (and (fboundp 'orderless-highlight-matches) (fboundp 'orderless-pattern-compiler)) (let* ((vnew #'...) (old (symbol-function ...))) (unwind-protect (progn (fset ... vnew) (cons ... hl)) (fset 'orderless-highlight-matches old))) (cons (apply #'completion-all-completions args) hl))) (fset #'completion-pcm--hilit-commonality old)))
  (progn (fset #'completion-hilit-commonality vnew) (let* ((vnew #'(lambda (pattern cands) (setq hl #'...) cands)) (old (symbol-function #'completion-pcm--hilit-commonality))) (unwind-protect (progn (fset #'completion-pcm--hilit-commonality vnew) (if (and (fboundp 'orderless-highlight-matches) (fboundp 'orderless-pattern-compiler)) (let* ((vnew ...) (old ...)) (unwind-protect (progn ... ...) (fset ... old))) (cons (apply #'completion-all-completions args) hl))) (fset #'completion-pcm--hilit-commonality old))))
  (unwind-protect (progn (fset #'completion-hilit-commonality vnew) (let* ((vnew #'(lambda (pattern cands) (setq hl ...) cands)) (old (symbol-function #'completion-pcm--hilit-commonality))) (unwind-protect (progn (fset #'completion-pcm--hilit-commonality vnew) (if (and (fboundp ...) (fboundp ...)) (let* (... ...) (unwind-protect ... ...)) (cons (apply ... args) hl))) (fset #'completion-pcm--hilit-commonality old)))) (fset #'completion-hilit-commonality old))
  (let* ((vnew #'(lambda (cands prefix &optional base) (setq hl #'(lambda ... ...)) (and cands (nconc cands base)))) (old (symbol-function #'completion-hilit-commonality))) (unwind-protect (progn (fset #'completion-hilit-commonality vnew) (let* ((vnew #'(lambda ... ... cands)) (old (symbol-function #'completion-pcm--hilit-commonality))) (unwind-protect (progn (fset #'completion-pcm--hilit-commonality vnew) (if (and ... ...) (let* ... ...) (cons ... hl))) (fset #'completion-pcm--hilit-commonality old)))) (fset #'completion-hilit-commonality old)))
  (let ((hl #'identity)) (let* ((vnew #'(lambda (cands prefix &optional base) (setq hl #'...) (and cands (nconc cands base)))) (old (symbol-function #'completion-hilit-commonality))) (unwind-protect (progn (fset #'completion-hilit-commonality vnew) (let* ((vnew #'...) (old (symbol-function ...))) (unwind-protect (progn (fset ... vnew) (if ... ... ...)) (fset #'completion-pcm--hilit-commonality old)))) (fset #'completion-hilit-commonality old))))
  (progn (fset #'completion-flex-all-completions vnew) (let ((hl #'identity)) (let* ((vnew #'(lambda (cands prefix &optional base) (setq hl ...) (and cands ...))) (old (symbol-function #'completion-hilit-commonality))) (unwind-protect (progn (fset #'completion-hilit-commonality vnew) (let* ((vnew ...) (old ...)) (unwind-protect (progn ... ...) (fset ... old)))) (fset #'completion-hilit-commonality old)))))
  (unwind-protect (progn (fset #'completion-flex-all-completions vnew) (let ((hl #'identity)) (let* ((vnew #'(lambda ... ... ...)) (old (symbol-function #'completion-hilit-commonality))) (unwind-protect (progn (fset #'completion-hilit-commonality vnew) (let* (... ...) (unwind-protect ... ...))) (fset #'completion-hilit-commonality old))))) (fset #'completion-flex-all-completions old))
  (let* ((vnew #'(lambda (&rest args) (let* ((vnew orig-pcm) (old ...)) (unwind-protect (progn ... ...) (fset ... old))))) (old (symbol-function #'completion-flex-all-completions))) (unwind-protect (progn (fset #'completion-flex-all-completions vnew) (let ((hl #'identity)) (let* ((vnew #'...) (old (symbol-function ...))) (unwind-protect (progn (fset ... vnew) (let* ... ...)) (fset #'completion-hilit-commonality old))))) (fset #'completion-flex-all-completions old)))
  (let ((orig-flex (symbol-function #'completion-flex-all-completions))) (let* ((vnew #'(lambda (&rest args) (let* (... ...) (unwind-protect ... ...)))) (old (symbol-function #'completion-flex-all-completions))) (unwind-protect (progn (fset #'completion-flex-all-completions vnew) (let ((hl #'identity)) (let* ((vnew ...) (old ...)) (unwind-protect (progn ... ...) (fset ... old))))) (fset #'completion-flex-all-completions old))))
  (let ((orig-pcm (symbol-function #'completion-pcm--hilit-commonality))) (let ((orig-flex (symbol-function #'completion-flex-all-completions))) (let* ((vnew #'(lambda (&rest args) (let* ... ...))) (old (symbol-function #'completion-flex-all-completions))) (unwind-protect (progn (fset #'completion-flex-all-completions vnew) (let ((hl ...)) (let* (... ...) (unwind-protect ... ...)))) (fset #'completion-flex-all-completions old)))))
  corfu--all-completions("" #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil 0 (metadata (category . company-elisp) (display-sort-function . identity) (cycle-sort-function . identity)))
  corfu--recompute-candidates("" 0 #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil)
  corfu--update-candidates("" 0 #f(compiled-function (str pred action) #<bytecode 0x66ddfffccdd2658>) nil)
  corfu--update()
  corfu--post-command()
```

</details>

**Comment by jojojames** [comment]
> Is the purpose of this fix for speed? 

Yes.

> If so, I think you can use shortcut at the beginning of fussy-all-completions when string is an empty string.

Which part?

> Also, a bug report. When I complete (with an empty string) in a following state in the *scratch* buffer:

Fixed.

**Comment by buzztaiki** [comment]
> Which part?

I was wondering if I could do the following, but it doesn't make much sense. Sorry.

```
(defun fussy-all-completions (string table pred point)
  (if (string-empty-p string)
      (all-completions string table pred)
    (setf fussy--hist-hash (fussy--history-hash-table))
```

> Fixed.

Thanks!

**Comment by buzztaiki** [comment]
I would like to skip sorting when the user input is an empty string.

**Comment by jojojames** [comment]
> I would like to skip sorting when the user input is an empty string.

It's handled here:

```
(defun fussy--adjust-metadata (metadata)
  "If actually doing filtering, adjust METADATA's sorting."
  (let ((flex-is-filtering-p
         ;; JT@2019-12-23: FIXME: this is kinda wrong.  What we need
         ;; to test here is "some input that actually leads/led to
         ;; flex filtering", not "something after the minibuffer
         ;; prompt".  E.g. The latter is always true for file
         ;; searches, meaning we'll be doing extra work when we
         ;; needn't.
         (or (not (window-minibuffer-p))
             (> (point-max) (minibuffer-prompt-end)))))
    `(metadata
      ,@(and flex-is-filtering-p
             `((display-sort-function . fussy--sort)))
      ,@(and flex-is-filtering-p
             `((cycle-sort-function . fussy--sort)))
      ,@(cdr metadata))))

```

The flex-is-filtering-p check was copied from the flex completion-style but could be tweaked to something fussy specific. Maybe we can track a buffer-local variable instead that fussy sets in all-completions.

Should probably create a new issue/PR for that though since that isn't completely related to this PR.

**Comment by jojojames** [comment]
I'm undecided on this implementation, it generally works but not a fan of it yet. May explore a simpler way to do this before merging.

**Comment by jojojames** [comment]
Closing in favor of https://github.com/jojojames/fussy/pull/22

**Pull request closed without merging**
