### PR TITLE
Use Eask for CI instead of Cask

### PR DESCRIPTION
**Pull request by jcs090218**
I would recommend people to use Eask instead of Cask. I have also added tests on `macOS` and `Windows`, see the log in https://github.com/jcs-PR/fussy/actions/runs/2434595880.

What's good about Eask? See blog https://jcs090218.github.io/blog/emacs-eask/#-then-why-eask-and-not-cask

### CODE REVIEW

**Comment by jojojames** [comment]
Nice, I'm only familiar with cask from other projects that I use cask with. I actually checked eask before I set up cask again and didn't find an easy 'eask in 1 minute' guide so went with cask.

For example, how to install eask on osx? For cask, it's just brew install cask.

As for the perf tests failing, that's pretty nice, I would've expected those tests not to be too stable given how machine specific they are. Will probably tweak later.

The osx question is the only question I had, since I'm often doing 'make test' right now.

**Comment by jcs090218** [comment]
There are various of way to install Eask, see https://emacs-eask.github.io/Getting-Started/Install-Eask/. Sorry, I have not add it to brew yet since I don't know how and the tool is still in early stages (looking to improve documentation someday). 😅 Anyway, the easiest way is to install it is from `npm`:

```
$ brew install node
$ npm install -g @emacs-eask/eask
```

I haven't look into tests yet but I guess you might be interested solving it. ;)

**Comment by jojojames** [comment]
Sounds good, I'll merge now and fix the tests later.

**Comment by jojojames** [comment]
Feel free to weak the CI as needed without a PR since I'm definitely not an expert there anyways.

**Comment by jcs090218** [comment]
Will do! Feel free to ask any questions! :)

**Pull request merged**
