### PR TITLE
Filter threshold accounts for different score backends

### PR DESCRIPTION
**Pull request by dangduc**
Introduce a new custom var that associates backends with threshold values: `fussy-score-threshold-to-filter-alist`.

By default, use the threshold in the alist. Use `0` as the threshold If backend not in alist.

`fussy-score-threshold-to-filter` is now used to override the alist.

### CODE REVIEW

**Comment by dangduc** [comment]
Fixes https://github.com/jojojames/fussy/issues/24

**Comment by dangduc** [comment]
In benchmarks on my computer, not seeing a material difference in speed with or without the alist.

**Comment by jojojames** [comment]
Result of 
```
(benchmark-run 100000
  (alist-get fussy-score-fn fussy-score-threshold-to-filter-alist))
```

?

**Comment by dangduc** [comment]
Was profiling `fussy-score`. Benchmarking closer to the change is better and... oh yeaa, it _is_ slow:

```emacs-lisp
(benchmark-run 100000
  (alist-get fussy-score-fn fussy-score-threshold-to-filter-alist))
; result (0.012986999999999999 0 0.0)

(let ((score '(-99)))
  (benchmark-run 100000
    (if fussy-score-threshold-to-filter
        (> (car score) fussy-score-threshold-to-filter)
      (> (car score)
         (or (alist-get fussy-score-fn
                        fussy-score-threshold-to-filter-alist)
             0)))))
; result: (0.019517 0 0.0)

(let ((score '(-99))
      (fussy-score-threshold-to-filter -100)) ; diff
  (benchmark-run 100000
    (if fussy-score-threshold-to-filter
        (> (car score) fussy-score-threshold-to-filter)
      (> (car score)
         (or (alist-get fussy-score-fn
                        fussy-score-threshold-to-filter-alist)
             0)))))
; result: (0.013395999999999998 0 0.0)
```

**Comment by dangduc** [comment]
Updated to cache the associated threshold into a new buffer local var.

Benchmark updated code (w/ alist w/ caching):
```emacs-lisp
(let ((score '(-99))
      (fussy-score-threshold-to-filter nil))
  (benchmark-run 100000
    (> (car score)
       (or fussy-score-threshold-to-filter
           fussy--score-threshold-to-filter-alist-cache
           (setq fussy--score-threshold-to-filter-alist-cache
                 (or (alist-get
                      fussy-score-fn
                      fussy-score-threshold-to-filter-alist)
                     0))))))
; (0.012351999999999998 0 0.0)

```

Benchmark of original code (w/o alist w/o caching):
```emacs-lisp
(let ((score '(-99)))
  (benchmark-run 100000
    (if fussy-score-threshold-to-filter
        (> (car score) fussy-score-threshold-to-filter)
      t)))
; (0.011210000000000001 0 0.0)
```

**Pull request merged**
